enum SfSymbols {
  personTextRectangleFill('person.text.rectangle.fill'),
  listBulletRectangleFill('list.bullet.rectangle.fill'),
  rectangleGrid1x2Fill('rectangle.grid.1x2.fill'),
  clipboardFill('clipboard.fill'),
  chartBarXaxis('chart.bar.xaxis'),
  listBulletClipboardFill('list.bullet.clipboard.fill'),
  personFillCheckmark('person.fill.checkmark'),
  personFillQuestionmark('person.fill.questionmark'),
  starSquareOnSquareFill('star.square.on.square.fill'),
  chartBarFill('chart.bar.fill'),
  brainHeadProfile('brain.head.profile'),
  heartTextSquareFill('heart.text.square.fill'),
  starSquareFill('star.square.fill'),
  trophyFill('trophy.fill'),
  graduationcapFill('graduationcap.fill'),
  rosette('rosette'),
  exclamationmarkBubbleFill('exclamationmark.bubble.fill'),
  docTextFill('doc.text.fill'),
  trashSquareFill('trash.square.fill'),
  pencilCircleFill('pencil.circle.fill'),
  plusAppFill('plus.app.fill'),
  plus('plus'),
  archiveboxFill('archivebox.fill'),
  doorLeftHandClosed('door.left.hand.closed'),
  folder('folder'),
  folderFill('folder.fill'),
  magazine('magazine'),
  magazineFill('magazine.fill'),
  gearshape('gearshape'),
  gearshapeFill('gearshape.fill'),
  personCheckmarkAndXmark('person.checkmark.and.xmark'),
  personFillCheckmarkAndXmark('person.fill.checkmark.and.xmark'),
  handRaised('hand.raised'),
  handRaisedFill('hand.raised.fill'),
  listBulletRectanglePortrait('list.bullet.rectangle.portrait'),
  listBulletRectanglePortraitFill('list.bullet.rectangle.portrait.fill'),
  gamecontroller('gamecontroller'),
  gamecontrollerFill('gamecontroller.fill'),
  dieFace5Fill('die.face.5.fill'),
  person3SequenceFill('person.3.sequence.fill'),
  calendarBadgeClock('calendar.badge.clock'),
  // face.smiling.inverse
  faceSmilingInverse('face.smiling.inverse'),
  person2Fill('person.2.fill'),
  checkmarkSealTextPageFill('checkmark.seal.text.page.fill'),
  // note.text.badge.plus
  noteTextBadgePlus('note.text.badge.plus'),
  hourglass('hourglass'),
  // printer.fill
  printerFill('printer.fill'),
  rectangle3GroupBubbleFill('rectangle.3.group.bubble.fill'),
  // arrow.right.square.fill
  arrowRightSquareFill('arrow.right.square.fill'),
  trashFill('trash.fill'),
  squareAndArrowDown('square.and.arrow.down'),
  printer('printer'),
  link('link'),
  arrowClockwise('arrow.clockwise'),
  more('ellipsis'),
  trash('trash');

  final String value;
  const SfSymbols(this.value);
}
